services:
  s3:
    build: docker
    restart: 'no'
    working_dir: /app
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - .:/app

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./docker/data/rustfs:/data
