version: '3'

services:
  s3-8.1:
    build: docker/8.1
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app

  s3-8.2:
    build: docker/8.2
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app

  s3-8.3:
    build: docker/8.3
    restart: 'no'
    working_dir: /app
    volumes:
      - .:/app

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./docker/data/minio:/data
    environment:
      - MINIO_ROOT_USER=root-username
      - MINIO_ROOT_PASSWORD=root-password
    command: server --console-address ":9090" /data