services:
  s3:
    build: docker
    restart: 'no'
    working_dir: /app
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - .:/app

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./docker/data/minio:/data
    environment:
      - MINIO_ROOT_USER=root-username
      - MINIO_ROOT_PASSWORD=root-password
    command: server --console-address ":9090" /data